### ISSUE TITLE
Proposal for a new API to get type and size info without unpack

### ISSUE THREAD

**Issue by tagomoris** [msgpack/msgpack-ruby#119]
MessagePack (serialized) binary has type info and size of (str/bin, array, map) at the header of whole binary.
When we want to know these, it's only way to unpack whole data. But it requires much computing power.

I propose a new API call to return an array of Hash object which contains:
- :type => (:nil, :string, :int, :float, :array, :map, :ext, ...)
- :size => (bits of numeric values, bytes of bin/str, length of elements of map/array, length of bytes of ext, ...)
- :id => ext type id (only for :ext)

A hash represents info of a msgpack object. The method scans all binary to build an array of it.

How do you think about this idea? @frsyuki

**Comment by tagomoris** [comment]
I really want this API to know the number of records from a binary transported via Fluentd's forward protocol w/o unpacking.

**Comment by nurse** [comment]
Just FYI, I'm implementing similar feature (but C layer) https://github.com/nurse/msgpack-ruby/blob/94af4e565a1a849740acd11ba7623df2faa0f84c/ext/msgpack/unpacker.c#L918

**Comment by tagomoris** [comment]
I found that what I really want is a method to know how many msgpack objects exist in a binary. Hmm.

**Comment by tagomoris** [comment]
I updated the description above. Is it still similar to yours?

**Comment by nurse** [comment]
Your proposal needs a cursor (or an API to really skip objects without allocating objects). Mime contains such implementation as a cursor, but yours seems to want to move the unpacker's position.

**Comment by frsyuki** [comment]
Doesn't `Unpacker#read_array_header` or `Unpacker#read_map_header` work?
It sounds good idea to add methods to tell:

* type of next value
* length of next str or bin
* type and length of next ext

**Comment by frsyuki** [comment]
Returning a class instance (immutable struct) is better than Hash in terms of performance.
I think it should be 2 methods because checking types needs only 1 byte but checking length need more bytes:

```ruby
class Unpacker
  #
  # Returns type of next value.
  # This peeks 1 byte from the underlaying internal buffer.
  #
  # :nil, :string. :integer, :float, :array, :map, ...
  #
  # @return Symbol
  def peek_next_type
  end

  #
  # Returns ValueInfo of next value.
  # This peeks 1 - 5 bytes from the underlaying internal buffer.
  #
  # @return ValueInfo or its subclass
  def peek_next_value_info
  end
end

class ValueInfo
  # Returns type of the value (:string, :binary, :integer, ...)
  def type
  end

  # Returns of size of string, binary, or extention value
  def size
  end

  alias_method :length, :size

  # Returns type id of extension value
  def ext_type_id
  end

  # Returns true if type is :string or :binary
  def raw?
  end

  # Returns true if type is :integer or :float
  def number?
  end
end
```

These are optional (My bet is that NOT adding them until some actually need them):

```
class Unpacker
  #
  # Returns format of next value
  #
  # :nil, :str8, :str16, :str32, :positive_fixint, :negative_fixint, ...
  # 
  def peek_next_format
  end
end
```

This is how msgpack-java designs data model around types:

* [ValueType](https://github.com/msgpack/msgpack-java/blob/develop/msgpack-core/src/main/java/org/msgpack/value/ValueType.java)
* [MessageFormat](https://github.com/msgpack/msgpack-java/blob/develop/msgpack-core/src/main/java/org/msgpack/core/MessageFormat.java)
* [ExtensionTypeHeader](https://github.com/msgpack/msgpack-java/blob/develop/msgpack-core/src/main/java/org/msgpack/core/ExtensionTypeHeader.java)

**Comment by frsyuki** [comment]
I think it's NOT good idea to add `read_next_type`. Because moving cursor makes internal state of the Unpacker unusable. There're no methods to read payload only.

Adding such method as like [msgpack-java does](https://github.com/msgpack/msgpack-java/blob/02117b7c322c56992984da90261a8d74da645a29/msgpack-core/src/main/java/org/msgpack/core/MessageUnpacker.java#L1271-L1298) is another idea but it will need `read_next_format` instead of `read_next_type` to return MessageFormat class. Because `read_next_type` doesn't tell length of the payload users need to read next. It's another topic.

**Comment by chrisseaton** [comment]
Is anyone actively requesting this API today? Does someone need it and they're having to do a hack to get around it? Anything like that?
