### ISSUE TITLE
Version 1.4.1 yanked?

### ISSUE THREAD

**Issue by severin** [msgpack/msgpack-ruby#207]
Hi, we had version 1.4.1 locked in our *Gemfile.lock* and noticed that installation started to fail recently. Installing that version "by hand" no longer works either:

```
gem install msgpack -v=1.4.1
ERROR:  Could not find a valid gem 'msgpack' (= 1.4.1) in any repository
```

What happened to 1.4.1?

**Comment by tagomoris** [comment]
1.4.1 was yanked because 1.4.1 (and 1.4.0) caused compilation errors on (very) old Ruby versions: https://github.com/msgpack/msgpack-ruby/issues/205
If we leave 1.4.1 on RubyGems, so many issues just like #205 would be reported for a very long time. I know yanked 1.4.1 is causing dependency errors right now, but it should have to be done for long-time maintenance cost reduction.
Thank you for your patience.

**Comment by severin** [comment]
Thanks for the explanation

**Comment by Charizard** [comment]
@tagomoris So, the right solution is to manually change deps in lockfile to point to 1.4.2?

**Comment by tagomoris** [comment]
@Charizard Exactly.

Much more people are updating their `.lock` so quickly than I expected (and it's used for Rails application dependency...).
The ideal solution was to leave 1.4.1 for a while, then yank it after people would update their dependency to 1.4.2.
But anyway, I'll keep `1.4.1` yanked, so, please update the locked `msgpack` version to `1.4.2`.
