### ISSUE TITLE
Support for Extended types?

### ISSUE THREAD

**Issue by alexgenco** [msgpack/msgpack-ruby#42]
It looks like there isn't support for [extended types](https://github.com/msgpack/msgpack/blob/master/spec.md#extension-type) yet, despite a stale pull request (https://github.com/msgpack/msgpack-ruby/pull/14).

Are there plans to implement it? It's a must-have to integrate with the [Neovim](https://github.com/neovim/neovim) MessagePack API. I would love to help but I've never written C in my life :disappointed: 

Great work with this! :smile:

**Comment by niamster** [comment]
Does it make sense to encode ruby symbols?
In my experience it's a bit annoying when existing RPC server code expects a symbol but unpacked message carries a string. When switching from ruby's native marshalling it's a big effort to check all the places for correctness(disallow sending symbols might be painful as those might be a part of nested arrays and checking everything is just a waste of CPU time).
Is is correct from msgpack point of view encode a type with possible native types(and indicating a fall-back)?

**Comment by nocelic** [comment]
@alexgenco we are working on this, I hope to have a proposal ready in a couple of days. 

@tagomoris moving my question form #52 to #42: 
Do we want the MRI code to match the JRuby code?
The JRuby code uses ExtensionValue class, which I do not really like. I think ExtType (form msgpack-python) or ExtensionValue or Extension or Extended would all have been better choices.
So we can
(a) Mirror the JRuby solution with ExtensionValue in MRI
(b) Change the JRuby code to match the MRI solution, whatever that will be.
(c) Write an optional JRuby compatibility layer in MRI
(d) Have separate interfaces for MRI and JRuby.

Personally, I'd go with (a) in order not to break any possibly existing code.
But before I proceed, I'd be happy to hear your opinion, so that I do not waste my time on something that will be rejected later.

**Comment by tagomoris** [comment]
(a) and/or (c) look good for me.
In sight of compatibility (a) is best, but (c) may be better than (a) if there're any idea to implement faster than (c). Best way to implement ext types may be different between MRI and JRuby.

I seriously need @frsyuki 's comment :smile:

**Comment by frsyuki** [comment]
It is good idea to add a Ruby class that corresponds to MessagePack's Extended type. msgpack-java has [org.msgpack.value.ExtendedValue](https://github.com/msgpack/msgpack-java/blob/v07-develop/msgpack-core/src/main/java/org/msgpack/value/ExtendedValue.java).

But I think implementation of Unpacker is not obvious. As like [this comment](https://github.com/msgpack/msgpack/issues/128#issuecomment-14066167), I want Unpacker to convert a application-defined Extended type to an application-defined Ruby class.

**Comment by frsyuki** [comment]
For example:

```ruby
# register timestamp type to Unpacker and Packer
unpacker.register_extended(0x7f) do |data|
  if data.length != 4
    raise MessagePack::MalformedFormatError, "Expected 4 bytes for Extended type 0x7f but got #{data.size} bytes"
  end
  Time.at(data.unpack('N'))
end
packer.register_extended(0x7f, Time) do |time|
  [time.to_i].pack('N')
end
```

or even lower level:

```ruby
# register timestamp type to Unpacker and Packer
unpacker.register_extended(0x7f) do |buffer,length|
  if length != 4
    raise MessagePack::MalformedFormatError, "Expected 4 bytes for Extended type 0x7f but got #{data.size} bytes"
  end
  Time.at(buffer.read_uint32)
end
packer.register_extended(Time) do |time,buffer|
  buffer.write_extended_header(0x7f, 4)
  buffer.write_uint32(time.to_i)
end
```

If a type is not registered, it is an unknown Extended type for applications. I want to reject unknown types when Unpacker receives data rather than visiting deserialized data recursively.

So, I think Unpacker needs a boolean option to control whether it uses the extended class or not when it deserializes an unknown extended type (like `Unpacker.new(extended_value: true)`).

**Comment by iconara** [comment]
For the record the `ExtensionValue` class in the JRuby implementation more or less only exists so that it can unpack any MessagePack stream. If it weren't there the unpacker would have to fail when an extension value was found. Think of it as something that wraps the bytes of an unsupported extension value.

**Comment by nocelic** [comment]
@frsyuki Excellent, now that the intention is clear it will be no problem to implement it. 

As for the choice of whether or not to deserializes an unknown extended type, I'd suggest the following generic solution: 

`Unpacker.new( extended_value: {nil|false|aClass} )`
with the following meanings:
- `nil`: take the default action. This would typically be a creation of a MessagePack::ExtendedValue instance
- `false`: reject, raise an Exception
- aClass: create instances of aClass

For `[un]packer.register_extended`, I'd go with all of the following possibilities:
a) Per @frsyuki, if a block is supplied, the extended payload will be yielded to it
b) If a callable object is given as the argument, it will be called with the extended payload 
c) If a class is given as the argument, its `from_msgpack` will be called on unpack, and `to_msgpack` on pack. 
d) if `false` is given, the type gets explicitly rejected
e) if `true` is given, the type is deregistered, and the defaults will be used

As a convenience for applications that create a multiple Packer or Unpacker instances with the same settings, I'd also provide the option for setting defaults in MessagePack::Packer/Unpacker classes, and use this as a fallback if Packer/Unpacker instances choose to default. 

If that sounds OK to you, I'll proceed with the implementation.

**Comment by nocelic** [comment]
@frsyuki @tagomoris @csfrancis

I have implemented the extended types functionality in this fork: 
https://github.com/nocelic/msgpack-ruby

The description is here: 
https://github.com/nocelic/msgpack-ruby/wiki#extended-types

Before I submit a PR, it would be great if you could take a look and tell me if anything needs to be changed. Thanks!

**Comment by tagomoris** [comment]
I'm very sorry that i don't have time to see the branch seriously for now... I'm willing to check it next week.

**Comment by frsyuki** [comment]
API draft:

```ruby
class Time
  def to_msgpack_ext
    [to_i].pack('N')
  end

  def self.from_msgpack_ext(data)
    Time.at(data.unpack('N')[0])
  end
end

packer = Packer.new
packer.register_type(-1, Time) {|time| [time.to_i].pack('N') }
packer.register_type(-1, Time, &:to_msgpack_ext)
packer.register_type(-1, Time, :to_msgpack_ext)

unpacker = Unpacker.new
unpacker.register_type(-1) {|data| Time.at(data.unpack('N')[0]) }
unpacker.register_type(-1, &Time.method(:from_msgpack_ext))
unpacker.register_type(-1, Time, :from_msgpack_ext)


factory = MessagePack::Factory.new
factory.register_type(-1, Time)
factory.register_type(-1, Time, packer: :to_msgpack_ext, unpacker: :from_msgpack_ext)
factory.register_type(-1, Time, packer: &:to_msgpack_ext, unpacker: &:from_msgpack_ext)
factory.register_type(-1, Time, packer: lambda {|time| ... }, unpacker: lambda {|time| ... })

packer = factory.packer
unpacker = factory.unpacker
```

**Comment by frsyuki** [comment]
For unknown extension value handling:

```ruby
MessagePack::Unpacker.new  # same with {allow_unknown_ext: false}, false is the default
MessagePack::Unpacker.new(allow_unknown_ext: true)
# if allow_unknown_ext is false, Unpacker throws an exception
# if allow_unknown_ext is true, Unpacker may return MessagePack::ExtensionValue

factory = MessagePack::Factory.new(unpacker: {allow_unknown_ext: true})
factory.unpacker  # same with Unpacker.new(allow_unknown_ext: true)
```

**Comment by nocelic** [comment]
@frsyuki: looks good, I can change the API to match your description. 

There just a few issues I would like to clarity: 

1) Regarding the Factory: 

    pk1 = factory.packer
    factory.register_type(0xab, .....)
    pk2 = factory.packer

Do pk1 and pk2 now have the same or a different idea about 0xab ext type? 
(I.e. do we reference, or do we copy the type registry of the Factory to the packers/unpackers it creates?) 
Personally, I'd prefer to reference because this can be a substitute for global defaults, but copying is better at avoiding surprises.

2) The low-level ext type handling (like in applications modifying the Buffer directly) is not a part of the proposed API. Since you mentioned the low-level access in an earlier example, is the omission of the low-level API intentional? 

3) In my implementation there are global defaults which can be set via the Packer/Unpacker classes. Are you sure you want no global defaults? 

4) If someone would like to change how unregistered types are handled, he would need to register his handler for every unregistered type (0..127). To make this process simpler, would you be OK with exposing a method to change the default from ExtensionValue to something else? 

5) factory.register_type(0x7f, Time, packer: &:to_msgpack_ext, unpacker: &:from_msgpack_ext)
will not work, blocks cannot be used that way. Would using procs be OK, like: 
factory.register_type( 0x7f, Time, packer: proc(...), unpacker: proc(...) )  ?

**Comment by tagomoris** [comment]
In my opinion:

1) copying makes less troubles than reference
By selecting copying, we have not to consider about many problems, ex: overwriting/overriding same type id between factories and instances.

2) I have no idea about this topic, but there seems not so many apps which want to handle low-level data representations.

3) Global default factory(singleton object as constant) seems useful

4) Converter for ExtensionValue seems not to be needed at the first implementation. Once we added it, then we cannot change its APIs.

5) `&:symbol` is just same with `:symbol.to_proc`, so it works

6) I have no idea about use case of that feature. Application must know about all knowledge about its typing. Can you explain about it?

**Comment by tagomoris** [comment]
@frsyuki how do you think about these?

**Comment by frsyuki** [comment]
1) I don't have use cases in my mind where layered registry is useful. I think simple copying is good enough.

2) I don't think low-level API is necessary at least for now. The low-level API I drafted exposes internal buffer during deserialization that can break some assumptions used for performance optimization.

3) it is useful for me to have global default factory such as `MessagePack::DefaultFactory` (= Factory.new).

**Comment by nocelic** [comment]
@tagomoris, @frsyuki: 

Thanks, I consider the questions 1-3 resolved.

4) If instead of 

    MessagePack::Unpacker.new(allow_unknown_ext: <true|false>)
we had 

    MessagePack::Unpacker.new(unknown_ext: <true|false|aClass>)
a user could easily substitute any class for `ExtensionValue`. The interface would be the same as for `ExtensionValue`, i.e. the substituted class would have to have `.new(type,data)` method and that is all. 
In my opinion, that would be a more powerful solution because it would allow the user to take some meaningful action instead of failing (option `false`) or ignoring the unknown type (option `true`). 

5)  `&:symbol` is the same as `&:symbol.to_proc`, not `:symbol.to_proc`. 
The proposed syntax results in a SyntaxError because it effectively tries to call a function with 2 blocks.

6) Example 1: a library you use or other developers on your project could reserve an exttype without telling you. To write more robust code, you could check that a type is not registered before you redefine it and break someone else's code.
Example 2: you want to add a default handler for a certain range of exttypes. You iterate through all of them and register the default handler only for those not already taken (previously registered). 

Also, without the getter methods, the symmetry of the Universe is broken :) 
(Seriously: they are so easy to implement that a user of the library would be more surprised to find they are not there than the other way around.)

**Comment by tagomoris** [comment]
> 4)
Your idea looks too complicated for me. How about to add option `:unknown_ext_class` to specify classes instead of `ExtensionValue`? It seems acceptable for me.

> 5)
You're right. It's good update idea to allow to feed procs instead of symbols.

> 6)
I got it. I will accept pull-requests for that feature...

**Comment by nocelic** [comment]
As I wrote, the purpose of my questions was to adapt my already existing and working solution for extended types (https://github.com/nocelic/msgpack-ruby) to your desired API and then issue a pull request. 
Considering that you have started working on a different solution (#71), my questions are of no relevance any more.

**Comment by tagomoris** [comment]
This is done by release of v0.7.0.

**Comment by alexgenco** [comment]
Thanks all :)
