### ISSUE TITLE
0.6.0 generates messages not decodable by msgpack-js 0.3.0

### ISSUE THREAD

**Issue by doughsay** [msgpack/msgpack-ruby#66]
This lib: https://github.com/creationix/msgpack-js

Can no longer decode messages that contain `|` (pipe) characters which are generated by msgpack-ruby 0.6.0.

msgpack-js throws this:

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: -590689048 trailing bytes
  at Object.decode (/var/www/pigeon/node_modules/socket.io-redis/node_modules/msgpack-js/msgpack.js:201:47)
  at Redis.onmessage (/var/www/pigeon/node_modules/socket.io-redis/index.js:94:24)
  at RedisClient.emit (events.js:106:17)
  at RedisClient.return_reply (/var/www/pigeon/node_modules/redis/index.js:696:22)
  at HiredisReplyParser.<anonymous> (/var/www/pigeon/node_modules/redis/index.js:321:14)
  at HiredisReplyParser.emit (events.js:95:17)
  at HiredisReplyParser.execute (/var/www/pigeon/node_modules/redis/lib/parser/hiredis.js:43:18)
  at RedisClient.on_data (/var/www/pigeon/node_modules/redis/index.js:547:27)
  at Socket.<anonymous> (/var/www/pigeon/node_modules/redis/index.js:102:14)
  at Socket.emit (events.js:95:17)
```

Don't know which packages fault it is...

**Comment by tagomoris** [comment]
@doughsay can you check whether msgpack-ruby can unpack that message or not?

**Comment by burnssun** [comment]
in my case
 
```ruby
require "msgpack"
puts "#{MessagePack::VERSION}"
p ({"a"=>"xxxxxx xxxxxxxxxxxxx xxxxxx xxxxx"}.to_msgpack)
```
output is 
```
0.6.0
"\x81\xA1a\xD9!xxxxxx xxxxxxxxxxxxx xxxxxx xxxxx"

0.5.12
"\x81\xA1a\xDA\x00!xxxxxx xxxxxxxxxxxxx xxxxxx xxxxx"

```

msgpack-ruby successfully unpack both case but mspack-js do not

**Comment by tagomoris** [comment]
It's depends on new spec of msgpack. `msgpack-js` seems not to support `str8` msgpack type.
MessagePack -ruby 0.6.0 packs data with latest MessagePack spec.
Please update `msgpack-js` or use any unpacker which supports latest MessagePack spec, or use msgpack-ruby 0.5.x to pack your data.

**Comment by pjanuario** [comment]
@tagomoris If this new release requires something new from MessagePack specification, so I would suggest this should be tagged as a Major version and not as Minor, since we are talking about a library that commonly used for integration and it could potentially broke happened with js integration.

**Comment by tagomoris** [comment]
@pjanuario What are you talking on? Semantic versioning?
If so, `0.y.z` APIs may be always broken by new versions. (FYI: http://semver.org/ item 4)

Of course, we want to help breaking everything. That's the reason why we'd bump up minor version.

I know that there's the other way to release 1.0.0. But there're no dists of msgpack implementations as versioned v1.0.0...

**Comment by pjanuario** [comment]
@tagomoris Sorry, about not mentioning it. 
Yes if the library is using semantic versioning, it should have been major, but if you consider that this is steel in "development" than it make sense. Is just weird, because the library as been developed for more than 2 years and I am pretty sure that a lot of people is using it in production, I am and it's stable.

Regarding, with the fact that there is no msgpack implementation with v.1, I think that one thing is library version another different thing is spec compliance and other libraries. So, if the library mentions the spec verison compliance should be ok to have major releases.

It just my 5 cents...

By the way, awesome work with the gem... I am using it production on a micro service infrastructure and receiving millions of messages a day using http://pjanuario.github.io/zmq-service-suite-specs/
