### ISSUE TITLE
Why TypeError is not subclass of UnpackError?

### ISSUE THREAD

**Issue by funny-falcon** [msgpack/msgpack-ruby#83]
It is strange, that MessagePack::TypeError is a separate species. Why it is not sublclass of UnpackError?

**Comment by frsyuki** [comment]
That "was" because of a plan to implement data type conversion module like msgpack-java's Template or jackson-dataformat-msgpack. MessageTypeException defined there can be thrown from "data type conversion module" which is not unpacker.
But it sounds confusing in msgpack-ruby. I created #85 to focus on this issue.
